pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        containers:
        - name: node
          image: node:16-alpine
          command:
          - cat
          tty: true
      """
    }
  }
  stages {
    stage('Test') {
      steps {
        container('node') {
          sh 'node --version'
        }
      }
    }
  }
}
